---
- name: check whether docker exists
  shell: command -v docker
  ignore_errors: True
  register: docker_installed

- include_tasks: install.yml
  when: docker_installed is failed

- name: install epel-release
  yum:
    name: epel-release
    state: present
  become: yes

- name: install pip
  yum:
    name: python-pip
    state: present
  become: yes

- name: install docker-py
  pip:
    name: docker
    state: present
    executable: pip
