- name: Create project directory
  file:
    path: /home/centos/project
    state: directory
    mode: '0755'

- name: Sync project
  synchronize:
    src: ../../../../../
    dest: /home/centos/project/api
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=infra"

- name: Build api image
  docker_image:
    name: api
    build:
      path: /home/centos/project/api
      pull: no
    source: build
    state: present
    force_absent: true
    force_source: true
    force_tag: true

- name: Create network
  docker_network:
    name: root_default

- name: Create api container
  docker_container:
    name: api
    image: api
    ports:
      - 8080:80
    restart_policy: unless-stopped
    state: started
    pull: no
    networks:
      - name: root_default

- name: Sync nginx.conf
  synchronize:
    src: ../files/nginx
    dest: /home/centos/project
  become: true

- name: Sync certificates
  synchronize:
    src: ../../../certificates/nw-challenge.bruno-yamada.com
    dest: /home/centos/project/nginx

- name: Nginx container
  docker_container:
    name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart_policy: unless-stopped
    volumes:
      - /home/centos/project/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/centos/project/nginx/default:/etc/nginx/sites-enabled/default
      - /home/centos/project/nginx/nw-challenge.bruno-yamada.com:/etc/nginx/ssl/nw-challenge.bruno-yamada.com
    state: started
    pull: yes
    networks:
      - name: root_default
